sudo: false

language: node_js
node_js:
- '8'
notifications:
  email: false
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: build 🔨
      script: npm run build
    - stage: deploy 📦
      if: branch = master
      script: npm run build:electron
      os: linux
      dist: xenial
    - if: branch = master
      script: npm run build:electron
      os: osx

